(function(){
	angular.module("appRouterModule",[])
			.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider){
				$urlRouterProvider.otherwise("/news/companyNews");
				$stateProvider
					//about路由
					.state("about",{
						url:"/about",
						templateUrl:"tpl/about.html"
					})
					.state("about.jianjie",{
						url:"/jianjie",
						templateUrl:"tpl/about/jianjie.html"
					})
					.state("about.building",{
						url:"/building",
						templateUrl:"tpl/about/building.html"
					})
					.state("about.join",{
						url:"/join",
						templateUrl:"tpl/about/join.html"
					})
					.state("about.contact",{
						url:"/contact",
						templateUrl:"tpl/about/contact.html"
					})
					//news 路由
					.state("news",{
						url:"/news",
						templateUrl:"tpl/news.html"
					})
					.state("news.bid",{
						url:"/bid",
						templateUrl:"tpl/news/bid.html"
					})
					.state("news.companyNews",{
						url:"/companyNews",
						templateUrl:"tpl/news/companyNews.html"
					})
					.state("news.active",{
						url:"/active",
						templateUrl:"tpl/news/active.html"
					})
					// exhibition 路由
					.state("exhibition",{
						url:"/exhibition",
						templateUrl:"tpl/exhibition.html"
					})
					.state("exhibition.planning",{
						url:"/planning",
						templateUrl:"tpl/exhibition/planning.html"
					})
					.state("exhibition.theme",{
						url:"/theme",
						templateUrl:"tpl/exhibition/theme.html"
					})
					.state("exhibition.museum",{
						url:"/museum",
						templateUrl:"tpl/exhibition/museum.html"
					})
					.state("exhibition.chanye",{
						url:"/chanye",
						templateUrl:"tpl/exhibition/chanye.html"
					})
					//  sandTable 路由
					.state("sandTable",{
						url:"/sandTable",
						templateUrl:"tpl/sandTable.html"
					})
					.state("sandTable.characteristic",{
						url:"/characteristic",
						templateUrl:"tpl/sandTable/characteristic.html"
					})
					.state("sandTable.technology",{
						url:"/technology",
						templateUrl:"tpl/sandTable/technology.html"
					})
					.state("sandTable.function",{
						url:"/function",
						templateUrl:"tpl/sandTable/function.html"
					})
					// CINEMA 路由
					.state("cinema",{
						url:"/cinema",
						templateUrl:"tpl/cinema.html"
					})
					.state("cinema.2D",{
						url:"/2D",
						templateUrl:"tpl/cinema/2D.html"
					})
					.state("cinema.3D",{
						url:"/3D",
						templateUrl:"tpl/cinema/3D.html"
					})
					.state("cinema.4D",{
						url:"/4D",
						templateUrl:"tpl/cinema/4D.html"
					})
					.state("cinema.5D",{
						url:"/5D",
						templateUrl:"tpl/cinema/5D.html"
					})
					.state("cinema.360",{
						url:"/360",
						templateUrl:"tpl/cinema/360.html"
					})
					.state("cinema.spherical",{
						url:"/spherical",
						templateUrl:"tpl/cinema/spherical.html"
					})
					.state("cinema.scene",{
						url:"/scene",
						templateUrl:"tpl/cinema/scene.html"
					})   
					.state("cinema.giant",{
						url:"/giant",
						templateUrl:"tpl/cinema/giant.html"
					})
					.state("cinema.meeting",{
						url:"/meeting",
						templateUrl:"tpl/cinema/meeting.html"
					})
					//MULTIMEDIA 路由
					.state("multimedia",{
						url:"/multimedia",
						templateUrl:"tpl/multimedia.html"
					})
					.state("multimedia.media1",{
						url:"/media1",
						templateUrl:"tpl/multimedia/media1.html"
					})
					.state("multimedia.media2",{
						url:"/media2",
						templateUrl:"tpl/multimedia/media2.html"
					})
					.state("multimedia.media3",{
						url:"/media3",
						templateUrl:"tpl/multimedia/media3.html"
					})
					.state("multimedia.media4",{
						url:"/media4",
						templateUrl:"tpl/multimedia/media4.html"
					})
					.state("multimedia.media5",{
						url:"/media5",
						templateUrl:"tpl/multimedia/media5.html"
					})
					.state("multimedia.media6",{
						url:"/media6",
						templateUrl:"tpl/multimedia/media6.html"
					})
					.state("multimedia.media7",{
						url:"/media7",
						templateUrl:"tpl/multimedia/media7.html"
					})
					.state("multimedia.media8",{
						url:"/media8",
						templateUrl:"tpl/multimedia/media8.html"
					})
					.state("multimedia.media9",{
						url:"/media9",
						templateUrl:"tpl/multimedia/media9.html"
					})
					.state("multimedia.media10",{
						url:"/media10",
						templateUrl:"tpl/multimedia/media10.html"
					})
					.state("multimedia.media11",{
						url:"/media11",
						templateUrl:"tpl/multimedia/media11.html"
					})
					.state("multimedia.media12",{
						url:"/media12",
						templateUrl:"tpl/multimedia/media12.html"
					})
					.state("multimedia.media13",{
						url:"/media13",
						templateUrl:"tpl/multimedia/media13.html"
					})
					// VIRYUAL 路由
					.state("viryual",{
						url:"/viryual",
						templateUrl:"tpl/viryual.html"
					})
					.state("viryual.bicycle",{
						url:"/bicycle",
						templateUrl:"tpl/viryual/bicycle.html"
					})
					.state("viryual.car",{
						url:"/car",
						templateUrl:"tpl/viryual/car.html"
					}) 
					.state("viryual.onsea",{
						url:"/onsea",
						templateUrl:"tpl/viryual/onsea.html"
					})
					.state("viryual.upsea",{
						url:"/upsea",
						templateUrl:"tpl/viryual/upsea.html"
					})
					.state("viryual.fly",{
						url:"/fly",
						templateUrl:"tpl/viryual/fly.html"
					})
					.state("viryual.port",{
						url:"/port",
						templateUrl:"tpl/viryual/port.html"
					})
					.state("viryual.airport",{
						url:"/airport",
						templateUrl:"tpl/viryual/airport.html"
					})
					// R&D 路由
					.state("innovate",{
						url:"/innovate",
						templateUrl:"tpl/innovate.html"
					}) 
					.state("innovate.chongming_item",{
						url:"/chongming_item",
						templateUrl:"tpl/innovate/chongming_item.html"
					}) 
					.state("innovate.daqing_item",{
						url:"/daqing_item",
						templateUrl:"tpl/innovate/daqing_item.html"
					})  
					.state("innovate.tianjin_item",{
						url:"/tianjin_item",
						templateUrl:"tpl/innovate/tianjin_item.html"
					})
					.state("innovate.hangzhou_item",{
						url:"/hangzhou_item",
						templateUrl:"tpl/innovate/hangzhou_item.html"
					})
					.state("innovate.xian_item",{
						url:"/xian_item",
						templateUrl:"tpl/innovate/xian_item.html"
					})
					.state("innovate.shenyang_item",{
						url:"/shenyang_item",
						templateUrl:"tpl/innovate/shenyang_item.html"
					})
			}])
})()